### ISSUE TITLE
Issue with the mod pack: possible incompatibility or conflict but cannot tell where

### ISSUE THREAD

**Issue by lordkabal26** [oiad/modPack#11]
Right click actions or deployables from toolbox are not working as expected (at all in fact)
Attached is a zip with our current PBOs and the latest RPT. I've been wracking my brain trying to figure this out for the last several days with no results.

[Server PBOs.zip](https://github.com/oiad/modPack/files/1722391/Server.PBOs.zip)

**Comment by oiad** [comment]
Hi there, 
I took a look at your files, you have made an editing error in your `scripts\clickActions\config.sqf`
```sqf
["ItemGPS","Range Down" ,"if(isNil 'DZE_CLICK_ACTIONS_GPS_RANGE') then {DZE_CLICK_ACTIONS_GPS_RANGE = 1500;};DZE_CLICK_ACTIONS_GPS_RANGE = (DZE_CLICK_ACTIONS_GPS_RANGE - 100) max 1000; format['GPS RANGE: %1',DZE_CLICK_ACTIONS_GPS_RANGE] call dayz_rollingMessages;","true"],
["ItemMap","Identify Keys","execVM 'scripts\locateVehicle.sqf';","true"]
["ItemRadio","Toggle Power","execVM 'scripts\radio\switch_on_off.sqf';","true"]
["ItemKey","Eject Passengers not in group","spawn remoteVehicle;","true",1]
["ItemKey","Toggle engine on/off","spawn remoteVehicle;","true",2]
["ItemKey","Unlock vehicle","spawn remoteVehicle;","true",3]
["ItemKey","Lock vehicle","spawn remoteVehicle;","true",4]
["ItemKey","Toggle Lights on/off","spawn remoteVehicle;","true",5]
```
They should have a comma at the end of them except for the last one.
Attached is a fixed version of your `config.sqf`
[config.zip](https://github.com/oiad/modPack/files/1722692/config.zip)

**Comment by lordkabal26** [comment]
ya know... I didn't even see that probably due to how my text editor scrolls the other three lines off the edge of my screen
