### ISSUE TITLE
Helicopter blows up after turning engine ON

### ISSUE THREAD

**Issue by nguyenph88** [oiad/modPack#12]
Hi Salival,

There is an issue when turning on the freshly bought Helicopter (without user's getting on it first). If we turn on the engine it will fly up and boom.

**Steps to reproduce:**
- Go to hero trader and buy any heli
- Without entering the heli, right click on the key and select "Engine On"

**Actual:**
- Heli will turn on the engine, fly up and lose control 
- It does not happen when users enter the heli, get off and start
- It also happens when getting the choppers out of the virtual garage

I've been messing with your code here:
https://github.com/oiad/modPack/blob/926964321c8d3b06895bbde42014e9eb1640a691/DayZ_Epoch_11.Chernarus/scripts/remoteVehicle/remoteVehicle.sqf#L104-L116

I could not find any better solution beside setting up a flag variable `isEnteredYet`. I don't show the "Engine On" option unless `isEnteredYet = 1`. Do you have any better solution for this?

Thank you.

**Comment by oiad** [comment]
Hello,
I can't reproduce this on my server (Chernarus) I purchased a UH60 at NEAF, it moves slightly but does not fly up

**Comment by nguyenph88** [comment]
I don't have any choppers in any AF traders (except jets), will test it again when I get home. Just bought UH60M_EP1_DZE from a hero trader (from your trader config in this modpack), started it and it flew up a little then dropped. It was damaged but not really destroyed like the big ones (merlin and chinook).

**Comment by nguyenph88** [comment]
i set it to NWAF or NEAF, the issue still persists. Since you cannot repro on your server, i tend to believe it's on my end. Here is the demo: https://www.youtube.com/watch?v=hYWi5sjo9bA

I also suspect it's because of the spawning point, tried to move that further away but still. Please close if this isn't an issue with the modpack. Thanks.

**Comment by oiad** [comment]
Hey,
I tried again with the same chopper you purchased at hero, Mine has buildables there but shouldn't matter too much.
https://www.youtube.com/watch?v=4ybiNHyRBI4&feature=youtu.be
I sent you an email to the one listed in your profile on here.
Cheers
