### ISSUE TITLE
Keep this repo in sync with other repos

### ISSUE THREAD

**Issue by nguyenph88** [oiad/modPack#6]
Hey,

Just wonder, how are you planing to keep this repo in sync with other repos? I saw some updates with virtualGarage but those changes are not reflected here.

Thanks

**Comment by oiad** [comment]
Hi,
Yes I'm definitely.going to be doing that. My main problem is time, over Xmas I took 2 weeks off and pretty much dedicated that to epoch/my mods. Now I'm back at work full time and have my own business also olus building a house time is a little short.

Also it's quite difficult to keep up with all the changes and sometimes they get missed.

**Comment by nguyenph88** [comment]
Hi,

Yeah I understand, we all seem like arma 2 vets ... I wasn't complaining, was just wondering how you plan to keep them all in sync. No big deal, I frequently check your repos so I will let you know if there are any issues with this mod pack.

Thanks and really appreciate your great work!
