### ISSUE TITLE
2 new issues with the new updates

### ISSUE THREAD

**Issue by nguyenph88** [oiad/modPack#8]
Hi,

I was trying to install your pack (with the latest changes) on a fresh server, 2 issues that I encountered so far:

1. In-game error for missing "dayz_server\compile\server_maintainArea.sqf" (I check and i see the file still in that folder)

2. When selecting "Virtual Garage" from a plotPole, RPT generates this issue:
(im running with ExtDB, overwatch and epoch in the param)

```
10:39:23 Error in expression < call compile format["%1",_key];
_key = _key select 1;

uiSleep (random .03);


>
10:39:23   Error position: <_key select 1;

uiSleep (random .03);


>
10:39:23   Error Undefined variable in expression: _key
10:39:23 File z\addons\dayz_server\compile\garage\fn_async.sqf, line 26
10:39:23 Error in expression < = "extDB" callExtension format["4:%1", _key];
if (_queryResult == "[5]") then {>
10:39:23   Error position: <_key];
if (_queryResult == "[5]") then {>
10:39:23   Error Undefined variable in expression: _key
10:39:23 File z\addons\dayz_server\compile\garage\fn_async.sqf, line 34
10:39:23 Error in expression <ult = call compile _queryResult;

if ((_queryResult select 0) == 0) exitWith {d>
10:39:23   Error position: <_queryResult select 0) == 0) exitWith {d>
10:39:23   Error Undefined variable in expression: _queryresult
10:39:23 File z\addons\dayz_server\compile\garage\fn_async.sqf, line 61
10:39:23 Error in expression <_asyncCall;

PVDZE_queryVehicleResult = _result;

if (!isNull _player) then {_cl>
10:39:23   Error position: <_result;

if (!isNull _player) then {_cl>
10:39:23   Error Undefined variable in expression: _result
10:39:23 File z\addons\dayz_server\compile\garage\server_queryVehicle.sqf, line 11
```

Please help when you have time. Thank you.

**Comment by oiad** [comment]
Hi Peter,
The first problem is with the latest infistar update, It looks like they are trying to access a server sided file from the client via PVS.
In AH.sqf find this line and delete it: 
```sqf
server_maintainArea_original = if(isNil 'server_maintainArea')then{compile preprocessFileLineNumbers '\z\addons\dayz_server\compile\server_maintainArea.sqf';}else{server_maintainArea};
```

Find this code block and delete it:
```sqf
			server_maintainArea = {
				private['_input','_player','_targetObj'];
				_input = _this select 1;
				_player = _input select 0;
				_targetObj = _input select 2;
				
				_log = format['%1(%2) maintained %3 (objid: %4) @%5 (%6)',name _player,getPlayerUID _player,typeOf _targetObj, _targetObj getvariable['ObjectID','0'],mapGridPosition _targetObj,getposatl _targetObj];
				['MAINTAIN',_log] call fn_custom_log;
				
				_input spawn server_maintainArea_original;
			};
```

For your second problem, I would say your extDB settings are incorrect and it can't connect to the database, check the @extDB\logs folder

**Comment by nguyenph88** [comment]
Thanks,

1. Fixed by removing those lines from new infiSTAR

2. Somehow the server automatically scans and removes the ExtDB.dll file so that was the code.

Also with this latest code, I don't see the right hand side icons for: food, water, temperature etc. Are they missing because of the new infiSTAR?

Thank you for your help

**Comment by oiad** [comment]
Icons on the right hand side you need to push F3.
It's the new feature for hidijg icons for streamers

On 18 January 2018 8:33:38 AM NZDT, Peter Nguyen <notifications@github.com> wrote:
>Thanks,
>
>1. Fixed by removing those lines from new infiSTAR
>
>2. Somehow the server automatically scans and removes the ExtDB.dll
>file so that was the code.
>
>Also with this latest code, I don't see the right hand side icons for:
>food, water, temperature etc. Are they missing because of the new
>infiSTAR?
>
>Thank you for your help
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/oiad/modPack/issues/8#issuecomment-358417268

-- 
Sent from my phone

**Comment by nguyenph88** [comment]
Thank you, this is resolved.
